---
- hosts: chkrootkit 
  vars:
    hello: Ansible
    chkrootkit_version: 0.55


  environment:
#    https_proxy: 
#    http_proxy: 
#    no_proxy: 

  tasks:
  - name: cp chkrootkit source 
    copy:
      src=Latest/
      dest=/opt/
      backup=yes
      force=yes
    tags: source 

  - name: Unarchive chkrootkit 
    unarchive:
      src: /opt/chkrootkit-{{chkrootkit_version}}.tar.gz
      dest: /opt
      copy: no
    tags: source 

  - name: cp chkrootkit scripts
    copy:
      src=scripts/chkrootkit_exec.sh
      dest=/opt/chkrootkit-{{chkrootkit_version}}/scripts/
      backup=yes
      force=yes
    tags: scripts 

  - name: set chkrootkit scripts
    shell: sed -e 's|^cd /opt/chkrootkit-x.xx|cd /opt/chkrootkit-{{chkrootkit_version}}|g' -i.bak /opt/chkrootkit-{{chkrootkit_version}}/scripts/chkrootkit_exec.sh
    tags: scripts 

  - name: set chkrootkit limits
    file:
      path=/opt/chkrootkit-{{chkrootkit_version}}
      state=directory
      owner=root
      group=root
      recurse=yes
    tags: limits 

  - name: create chkrootkit log file 1
    file:
      path=/var/log/chkrootkit/
      state=directory
      owner=root
      group=root
      mode=755
    tags: logfile 

  - name: create chkrootkit cron
    cron:
      hour=1
      minute=30
      weekday=1
      job="sh /opt/chkrootkit-{{chkrootkit_version}}/scripts/chkrootkit_exec.sh"
    tags: createcron
